/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/layouts/AppHeader/AppHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    ButtonsView: typeof import('./src/views/ButtonsView.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Drawer: typeof import('primevue/drawer')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    PrimeVueButtons: typeof import('./src/components/PrimeVueButtons.vue')['default']
    PrimeVueConfirmDialog: typeof import('./src/components/PrimeVueConfirmDialog.vue')['default']
    PrimeVueDataTable: typeof import('./src/components/PrimeVueDataTable.vue')['default']
    PrimeVueDrawer: typeof import('./src/components/PrimeVueDrawer.vue')['default']
    PrimeVueSpeedDial: typeof import('./src/components/PrimeVueSpeedDial.vue')['default']
    PrimeVueSplitButton: typeof import('./src/components/PrimeVueSplitButton.vue')['default']
    PrimeVueStepper: typeof import('./src/components/PrimeVueStepper.vue')['default']
    PrimeVueTollbar: typeof import('./src/components/PrimeVueTollbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SpeedDial: typeof import('primevue/speeddial')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tailwind: typeof import('./src/components/Tailwind.vue')['default']
    TailwindBase: typeof import('./src/components/TailwindBase.vue')['default']
    TailwindStates: typeof import('./src/components/TailwindStates.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
